apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-transacciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-transacciones
  template:
    metadata:
      labels:
        app: app-transacciones
    spec:
      containers:
        - name: app-transacciones
          image: nali1312/app-transacciones:arm
          ports:
            - containerPort: 9090
          env:
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: "postgresql"
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "joss"
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: "Nali1312@"
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://mweb2.postgres.database.azure.com/transacciones"
            - name: QUARKUS_DATASOURCE_JDBC_MAX_SIZE
              value: "2"
            - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
              value: "update"
            - name: QUARKUS_LOG_CATEGORY_ORG_HIBERNATE_LEVEL
              value: "INFO"
            - name: QUARKUS_HTTP_PORT
              value: "9090"
            - name: QUARKUS_HTTP_CORS
              value: "true"
            - name: QUARKUS_HTTP_CORS_ORIGINS
              value: "*"
            - name: QUARKUS_HTTP_CORS_METHODS
              value: "GET,PUT,POST,DELETE,PATCH,OPTIONS"
            - name: QUARKUS_HTTP_CORS_HEADERS
              value: "Authorization,Content-Type,Access-Control-Allow-Origin"
            - name: QUARKUS_RESTEASY_CHARSET
              value: "UTF-8"
            # Inventario REST client
            - name: APP_INVENTARIO_URL
              value: "http://app-inventario-service:8080"
            - name: INVENTARIORESTCLIENT_MP_REST_URL
              value: "http://app-inventario-service:8080"
            # OIDC
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value: "https://api.markweb.store/realms/mweb"
            - name: QUARKUS_OIDC_CLIENT_ID
              value: "mweb-jkmoncayo"
            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              value: "QdIBNMDSELsBbCwYfxeciHPLLOZMntX8"
            - name: QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL
              value: "https://api.markweb.store/realms/mweb"
            - name: QUARKUS_OIDC_CLIENT_CLIENT_ID
              value: "mweb-jkmoncayo"
            - name: QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET
              value: "QdIBNMDSELsBbCwYfxeciHPLLOZMntX8"
            - name: QUARKUS_OIDC_CLIENT_DISCOVERY_ENABLED
              value: "true"
            - name: QUARKUS_OIDC_CLIENT_TOKEN_PATH
              value: "/protocol/openid-connect/tokens"
            - name: QUARKUS_OIDC_APPLICATION_TYPE
              value: "service"
            - name: KEYCLOAK_REALM
              value: "mweb"
---
apiVersion: v1
kind: Service
metadata:
  name: app-transacciones-service
spec:
  selector:
    app: app-transacciones
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP

