apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gestion-cajas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-gestion-cajas
  template:
    metadata:
      labels:
        app: app-gestion-cajas
    spec:
      containers:
        - name: app-gestion-cajas
          image: nali1312/app-gestion-cajas:arm
          ports:
            - containerPort: 9091
          env:
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: "postgresql"
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "joss"
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: "Nali1312@"
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://mweb2.postgres.database.azure.com/gestion-cajas"
            - name: QUARKUS_DATASOURCE_JDBC_MAX_SIZE
              value: "2"
            - name: QUARKUS_HTTP_PORT
              value: "9091"
            - name: QUARKUS_HTTP_CORS
              value: "true"
            - name: QUARKUS_HTTP_CORS_ORIGINS
              value: ".*"
            - name: QUARKUS_HTTP_CORS_METHODS
              value: "GET,PUT,POST,DELETE,PATCH,OPTIONS"
            - name: QUARKUS_HTTP_CORS_HEADERS
              value: "Authorization,Content-Type,Access-Control-Allow-Origin"
            - name: QUARKUS_RESTEASY_CHARSET
              value: "UTF-8"
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value: "https://api.markweb.store/realms/mweb"
            - name: QUARKUS_OIDC_CLIENT_ID
              value: "mweb-jkmoncayo"
            - name: QUARKUS_OIDC_CREDENTIALS_SECRET
              value: "QdIBNMDSELsBbCwYfxeciHPLLOZMntX8"
            - name: QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL
              value: "https://api.markweb.store/realms/mweb"
            - name: QUARKUS_OIDC_CLIENT_CLIENT_ID
              value: "mweb-jkmoncayo"
            - name: QUARKUS_OIDC_CLIENT_DISCOVERY_ENABLED
              value: "false"
            - name: QUARKUS_OIDC_CLIENT_TOKEN_PATH
              value: "/protocol/openid-connect/tokens"
            - name: KEYCLOAK_REALM
              value: "mweb"
---
apiVersion: v1
kind: Service
metadata:
  name: app-gestion-cajas-service
spec:
  selector:
    app: app-gestion-cajas
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP
